# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/GreenEnergyHub.Charges"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/source/Energinet.Charges.Libraries"
    schedule:
      interval: "monthly"
