# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Publish Clients.Registration to Nuget.org

on:
  push:
    branches:
      - main
    paths:
      - source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/**
      - .github/workflows/clients-registration-publish.yml
      - .github/actions/dotnet-publish-nuget/**
  # The purpose of the pull-request trigger is to have the PR gate verify that the NuGet package version number
  # isn't already published - in order to avoid breaking main
  # And to publish pre-release versions.
  pull_request:
      branches:
        - main
      paths:
      - source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/**
      - .github/workflows/clients-registration-publish.yml
      - .github/actions/dotnet-publish-nuget/**
  workflow_dispatch: {}

env:
  DOTNET_VERSION: '6.0.300'
  CSPROJ_FILE_PATH: 'source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj'
  BINARY_PATH: 'source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/bin/Release/*.nupkg'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Publish to nuget feed
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Pack and publish nuget package
        uses: ./.github/actions/dotnet-publish-nuget
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}
          csproj_file_path: ${{ env.CSPROJ_FILE_PATH }}
          binary_path: ${{ env.BINARY_PATH }}
          nuget_token: ${{ secrets.NUGET_TOKEN }}
          nuget_recurse_path: source/Energinet.Charges.Libraries
